name: Parallel Matrix Docker Builds

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  REGISTRY: docker.io
  USERNAME: ${{ secrets.DOCKER_USERNAME }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - context: ./browser
            tag: basescript-browser
          - context: ./compiler
            tag: basescript-compiler
          - context: ./playground
            tag: basescript-playground

    steps:
      - name: Checkout source with submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive  

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.USERNAME }}/${{ matrix.tag }}:latest