services:
    nginx:
      image: nginx:latest
      restart: unless-stopped
      ports:
        - 80:80
      volumes:
        - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
      networks:
        - bs-net
      depends_on:
        - compiler
        - playground
        - browser

    compiler:
      image: nishithp/basescript-compiler
      restart: unless-stopped
      ports:
        - 3000:3000
      build: ./compiler
      env_file: ./compiler/.env
      networks:
        - bs-net
        
    redis:
      image: redis
      restart: unless-stopped
      ports:
        - 6379:6379
      volumes:
        - redis_data:/data
      networks:
        - bs-net
    
    browser:
      image: nishithp/basescript-browser
      restart: unless-stopped
      ports:
        - 9222:9222     # Direct Chrome DevTools access
        - 8080:8080     # Caddy reverse proxy
        - 7900:7900     # VNC
        - 4444:4444     # Selenium Browser Hub
      build: ./browser
      environment:
        - REDIS_HOST=redis
        - REDIS_PORT=6379
      networks:
        - bs-net
      depends_on: 
        - redis
    
    playground:
      image: nishithp/basescript-playground
      restart: unless-stopped
      # ports:
        # - 80:80
      build: ./playground
      environment:
        # - VITE_BACKEND_URL=http://localhost:3000
        - VITE_BACKEND_URL=/api
      networks:
        - bs-net
      depends_on:
        - browser
        - redis
        - compiler
    
volumes:
  redis_data:

networks:
  bs-net:
    driver: bridge
